/**
 * Visualization Page - AI-Powered Data Visualizations
 *
 * Displays interactive visualizations generated by Claude AI based on
 * query results from the Analytics page. Shows AI-recommended chart types
 * that best represent the analytical context of the data.
 *
 * Features:
 * - AI-driven chart type selection
 * - Interactive Plotly visualizations
 * - Visualization reasoning display
 * - Fallback logic for missing specs
 * - Empty state guidance
 */

import { useMemo } from 'react'
import { useQueryStore } from '@/stores/queryStore'
import { PlotlyChart } from '@/components/charts/PlotlyChart'
import { getVisualizationOrFallback } from '@/utils/chartRecommendations'

export default function VisualizationPage() {
  const currentQuery = useQueryStore((state) => state.currentQuery)

  // Get visualization spec (AI-provided or fallback)
  const visualizationSpec = useMemo(() => {
    if (!currentQuery) return null

    return getVisualizationOrFallback(
      currentQuery.visualizationSpec,
      currentQuery.results,
      currentQuery.question
    )
  }, [currentQuery])

  // Empty state - no query yet
  if (!currentQuery) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] space-y-6">
        <div className="w-32 h-32 rounded-full bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center">
          <svg
            className="w-16 h-16 text-primary"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
            />
          </svg>
        </div>

        <div className="text-center space-y-2 max-w-md">
          <h3 className="text-xl font-semibold text-foreground">
            No Visualization Yet
          </h3>
          <p className="text-sm text-muted-foreground">
            Ask a question in the Analytics tab to see AI-powered visualizations here.
            Claude will automatically recommend the best chart type for your data.
          </p>
        </div>

        <div className="flex flex-col gap-2 text-sm text-muted-foreground">
          <p className="flex items-center gap-2">
            <svg className="w-4 h-4 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            Interactive charts with zoom, pan, and export
          </p>
          <p className="flex items-center gap-2">
            <svg className="w-4 h-4 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            AI-recommended chart types that match your analysis
          </p>
          <p className="flex items-center gap-2">
            <svg className="w-4 h-4 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            Reasoning explanation for chart selection
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6 fade-in">
      {/* Header Section */}
      <div className="bg-gradient-to-r from-card to-muted/30 p-6 rounded-xl border-2 border-border shadow-lg">
        <div className="flex items-start gap-4">
          <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
            <svg
              className="w-6 h-6 text-primary"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
              />
            </svg>
          </div>

          <div className="flex-1 space-y-2">
            <h2 className="text-lg font-semibold text-foreground">
              AI-Generated Visualization
            </h2>
            <p className="text-sm text-muted-foreground">
              Question: <span className="font-medium text-foreground">{currentQuery.question}</span>
            </p>

            {/* Query Stats */}
            <div className="flex flex-wrap gap-4 text-xs text-muted-foreground mt-3">
              <div className="flex items-center gap-1">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 7v10c0 2 1 3 3 3h10c2 0 3-1 3-3V7c0-2-1-3-3-3H7C5 4 4 5 4 7z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 2v5M8 2v5M4 9h16" />
                </svg>
                {currentQuery.results.rowCount.toLocaleString()} rows
              </div>
              <div className="flex items-center gap-1">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7" />
                </svg>
                {currentQuery.results.columns.length} columns
              </div>
              <div className="flex items-center gap-1">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                {currentQuery.executionTimeMs}ms
              </div>
              {currentQuery.visualizationSpec && (
                <div className="flex items-center gap-1">
                  <svg className="w-4 h-4 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                  </svg>
                  AI-Recommended
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Visualization Section */}
      <div className="slide-in">
        <PlotlyChart
          results={currentQuery.results}
          visualizationSpec={visualizationSpec || undefined}
        />
      </div>

      {/* AI Summary Section */}
      {currentQuery.aiSummary && (
        <div className="bg-card rounded-xl border border-border p-6 space-y-3">
          <h3 className="text-sm font-semibold text-foreground flex items-center gap-2">
            <svg className="w-5 h-5 text-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
            </svg>
            AI Analysis
          </h3>
          <p className="text-sm text-muted-foreground leading-relaxed">
            {currentQuery.aiSummary}
          </p>
        </div>
      )}

      {/* SQL Query Section - Collapsible */}
      <details className="bg-card rounded-xl border border-border overflow-hidden">
        <summary className="px-6 py-4 cursor-pointer hover:bg-muted/50 transition-colors flex items-center justify-between">
          <span className="text-sm font-semibold text-foreground flex items-center gap-2">
            <svg className="w-5 h-5 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
            </svg>
            View Generated SQL
          </span>
          <svg className="w-4 h-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </summary>
        <div className="px-6 pb-4">
          <pre className="bg-muted p-4 rounded-lg text-xs overflow-x-auto">
            <code className="text-foreground">{currentQuery.sql}</code>
          </pre>
        </div>
      </details>
    </div>
  )
}
